server.port=8081
spring.application.name=taxi_project
telegram.bot.token=8906086545:AAGTh2flIwBHDyR_GMgLc_jyfAUsGimc7Fg
telegram.bot.username=shaharlar_aro_bot

spring.datasource.url=jdbc:postgresql://localhost:5432/taxi_db
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Swagger uchun faqat shu 3 ta qator yetarli (Java Config borligi uchun)
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.taxi_project

spring.output.ansi.enabled=always

jwt.secret=bXlTdXBlclNlY3JldEtleVRoYXRJc0xvbmdFbm91Z2gxMjM=
spring.thymeleaf.check-template-location=false
-Djava.net.preferIPv4Stack=true

secret.key=MeningJudaHamMaxfiyKalitim123456
spring.jpa.open-in-view=false